config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # rucaptcha
  mount RuCaptcha::Engine => "/rucaptcha"

  #
  # Upload Area
  #

  post 'image' => 'upload#upload_image'
  post 'image_base64' => 'upload#upload_base64_image'
  post 'upload_avatar' => 'upload#upload_avatar'

  #
  # Blog Area
  #
  resources :posts, path: :blog, except: [:index] do
    resources :comments, only: [:create]
  end
  resources :tags, only: [:index, :show]
  resources :columns, only: [:index, :show]

  #
  # Search
  #

  get 'search' => 'search#search'

  #
  # Admin Area
  #
  namespace :admin do
    root to: "dashboard#index"
    resources :posts
    resources :comments, only: [:index, :create, :update, :destroy]
    resources :columns, except: [:update] do
      collection do
        put :update_column
      end
    end
    resources :tags, except: [:update] do
      collection do
        put :update_tag
      end
    end
    resources :pages
    resource :settings, only: [:show, :create]
  end

  #
  # User Area
  #
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root to: 'posts#index'

  #
  # Page Area
  #
  resources :pages, only: [:show], path: "/" do
    resources :comments, only: [:create]
  end

end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  posts_count :integer          default(0)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Tag < ApplicationRecord

  has_many :post_tag_refs
  has_many :posts, through: :post_tag_refs

  validates :name, uniqueness: true, presence: true

  def to_param
    name
  end

  def saved?
    id && persisted?
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::ApplicationController
  before_action :set_tag, only: [:destroy]

  def index
    @tags = Tag.all.page(params[:page])
    @tag = Tag.new
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      @tag.save
      format.js
    end
  end

  def update_tag
    @tag = Tag.find_by_id(params[:id])
    if @tag.update(tag_params)
      render json: {status: 1, message: '更新成功!', data: {path: tag_path(@tag)}}
    else
      render json: {status: 0, message: @tag.errors}
    end
  end

  def destroy
    @tag = @tag.destroy
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find_by_name(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find_by_name(params[:id])
    @posts = @tag.posts.includes(:tags, :column).page(params[:page]).per(8)
  end

end

app/helpers/tags_helper.rb
module TagsHelper
  def highlight_class(tag)
    tag.nil? ? '' : 'filter-highlight'
  end
end

app/views/admin/tags/_index.html.haml
%ol.breadcrumb
  %li
    %i.fa.fa-dashboard.fa-prl5
    = link_to admin_root_path do
      管理首页
  %li.active
    %i.fa.fa-tags.fa-prl5
    标签管理
#admin-tag-index
  = form_for [:admin, @tag], remote: true do |f|
    .table-responsive
      %table.table.table-bordered.table-hover.table-striped
        %thead
          %tr
            %th ID
            %th 名称
            %th 文章数
            %th 创建时间
            %th 操作
        %tbody
          - @tags.each do |t|
            %tr{id: "tag-#{t.id}"}
              %td.id
                = t.id
              %td.name{style:'width: 25%'}
                = t.name
              %td
                = t.posts_count || 0
              %td
                = t.created_at.localtime.strftime("%x %H:%M")
              %td.operate-icons
                .fa.fa-pencil-square.fa-prl5.has-tooltip{ 'data-original-title' => '修改此标签', 'data-placement' => 'top', 'data-toggle' => 'tooltip', onclick: "editTag(#{t.id})"}
                = link_to admin_tag_path(t), method: :delete, remote: true, data: {confirm: '删除后，有此标签的文章将无此标签，确认删除？'},
                  class: 'has-tooltip', 'data-original-title' => '删除此标签', 'data-placement' => 'top', 'data-toggle' => 'tooltip' do
                  .fa.fa-trash.fa-pr5
                = link_to t, class:'has-tooltip overview', 'data-original-title' => '查看', 'data-placement' => 'top', 'data-toggle' => 'tooltip', target: '_blank' do
                  .fa.fa-eye
          %tr.tags-create-field
            %td
            %td
              = f.text_field :name, class: 'form-control', placeholder: '请输入标签', required: true
            %td{colspan: 3}
              = f.submit '创建', class: 'btn btn-success margin-right-5'
              .btn.btn-default.cancle-tag-field
                取消
          %tr.add-tags-btn
            %td.td-button{colspan: 6}
              .fa.fa-plus.fa-pr5.table-bottom-btn
                添加标签
= paginate @tags, remote: true

:coffee
  $('.add-tags-btn').click ->
    $('.add-tags-btn').hide()
    $('.tags-create-field').show()
    return
  $('.cancle-tag-field').click ->
    $('.add-tags-btn').show()
    $('.tags-create-field').hide()
    return
  $('#new_tag').submit ->
    $('input[type=submit]', this).attr 'disabled', 'disabled'
    return

:javascript
  function editTag(id){
    tag = $('#tag-'+id)
    name = tag.find('.name').text()
    html = "<tr id='edit-tag-" + id + "'><td>" + id + "<input type='hidden' name='tag_id' id='tag_id' value='" + id + "'></td><td style='width: 25%'><input type='text' name='name' id='name' value='" + name + "' class='form-control'></td><td colspan='3'><div class='btn btn-success margin-right-5' onclick='updateTag(" + id + ")'>修改</div><div class='btn btn-default cancle-edit-field' onclick='cancleEdit(" + id + ")'>取消</div></td></tr>"
    tag.after(html)
    tag.hide()
  }
  function cancleEdit(id){
    $('#edit-tag-' + id).remove()
    $('#tag-'+id).show()
  }
  function updateTag(id){
    edit_tag = $('#edit-tag-'+id)
    tag = $('#tag-'+id)
    name = edit_tag.find('#name').val()
    if(name == ''){
      alert('标签不能为空')
      return
    }
    $.ajax({
      url: '/admin/tags/update_tag',
      data: {'id': id,'tag[name]': name},
      type: "PUT",
      beforeSend: function(data) {
        edit_tag.find('.btn-success').append('<i class="fa fa-spinner fa-pulse fa-fw"></i>')
      },
      success: function(data) {
        if(data.status == '1'){
          tag.find('.overview').attr('href', data.data.path)
          edit_tag.remove()
          tag.find('.name').text(name)
          tag.show()
        }else{
          alert(data.message)
        }
      }
    })
  }

app/views/admin/tags/create.js.haml
- if @tag.saved?
  :plain
    html = "<tr id='tag-#{@tag.id}'><td>#{@tag.id}</td><td class='name'>#{@tag.name}</td><td>0</td><td>#{@tag.created_at.localtime.strftime('%x %H:%M')}</td><td class='operate-icons'><div class='fa fa-pencil-square fa-prl5 has-tooltip' data-original-title='修改此标签' data-placement='top' data-toggle='tooltip' onclick='editTag(#{@tag.id})'></div><a data-confirm='删除后不能恢复，确认删除？' class='has-tooltip' data-original-title='删除此标签' data-placement='top' data-toggle='tooltip' data-remote='true' rel='nofollow' data-method='delete' href='#{admin_tag_path(@tag)}'><div class='fa fa-trash fa-pr5'></div></a><a class='has-tooltip overview' data-original-title='查看' data-placement='top' data-toggle='tooltip' href='#{tag_path(@tag)}' target='_blank'><div class='fa fa-eye'></div></a></div></td></tr>";
    $('.tags-create-field').before(html)
    $('#new_tag')[0].reset()
    notifyTop("创建成功！");
- else
  :plain
    alert('输入有误，请稍后重试!');

app/views/admin/tags/destroy.js.haml
- if @tag.destroyed?
  :plain
    $('#tag-#{@tag.id}').hide()
    notifyTop("删除成功！");
- else
  :plain
    alert('删除失败,请稍后重试!');

app/views/admin/tags/index.html.haml
- title '标签管理'
= render 'index'

app/views/admin/tags/index.js.haml
:plain
  $("#page-wrapper").html("#{escape_javascript(render('index'))}");
  $('.side-nav .active').removeClass('active')
  $('.side-nav .admin-tag').addClass('active')